<a href="https://colab.research.google.com/github/raghavxi1/gym-attendance-analysis/blob/main/notebooks/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd, numpy as np
from google.colab import files
files.upload()

Saving daily_gym_attendance_workout_data.csv to daily_gym_attendance_workout_data.csv

{'daily_gym_attendance_workout_data.csv': b'member_id,visit_date,age,gender,membership_type,workout_type,workout_duration_minutes,calories_burned,check_in_time,attendance_status\n1,2024-10-11,64,Other,Annual,HIIT,28,171,20:04,Absent\n2,2024-06-01,65,Female,Quarterly,Strength Training,72,650,19:17,Absent\n3,2024-06-13,45,Male,Quarterly,Cardio,70,633,7:24,Absent\n4,2024-02-05,35,Female,Monthly,CrossFit,64,362,7:18,Absent\n5,2024-07-13,26,Female,Quarterly,Yoga,31,262,11:22,Absent\n6,2024-09-11,45,Other,Quarterly,Cardio,63,518,20:08,Present\n7,2024-02-22,30,Other,Quarterly,CrossFit,50,404,18:17,Absent\n8,2024-05-04,38,Male,Annual,Yoga,99,959,21:59,Absent\n9,2024-02-10,61,Female,Monthly,CrossFit,36,289,9:39,Present\n10,2024-08-14,36,Other,Quarterly,Strength Training,94,643,11:29,Absent\n11,2024-10-11,60,Female,Monthly,Strength Training,110,738,22:43,Present\n12,2024-12-25,26,Female,Monthly,HIIT,86,547,8:17,Absent\n13,2024-06-28,48,Female,Quarterly,HIIT,44,389,19:08,Absent\n14,2024-12-01,54,Other,Annual,Yoga,99,644,14:45,Absent\n15,2024-07-08,40,Other,Quarterly,CrossFit,99,643,20:18,Present\n16,2024-10-05,38,Other,Monthly,HIIT,106,976,13:15,Absent\n17,2024-12-01,28,Other,Monthly,Yoga,34,244,9:13,Present\n18,2024-06-27,35,Other,Annual,CrossFit,25,211,18:38,Present\n19,2024-10-31,32,Female,Annual,CrossFit,55,402,9:06,Present\n20,2024-07-31,32,Female,Monthly,CrossFit,48,330,10:35,Present\n21,2024-01-02,51,Other,Monthly,Cardio,68,526,16:58,Absent\n22,2024-07-28,53,Female,Annual,HIIT,41,248,14:24,Absent\n23,2024-05-06,30,Male,Quarterly,HIIT,98,577,20:49,Absent\n24,2024-07-31,20,Male,Monthly,CrossFit,104,589,21:37,Present\n25,2024-12-07,63,Male,Annual,Yoga,54,288,12:09,Present\n26,2024-09-23,21,Female,Annual,Yoga,40,358,14:09,Absent\n27,2024-06-12,52,Male,Monthly,CrossFit,77,620,14:48,Absent\n28,2024-05-02,49,Other,Annual,HIIT,37,187,19:56,Absent\n29,2024-02-07,39,Other,Quarterly,Strength Training,120,991,21:23,Present\n30,2024-12-02,57,Female,Annual,CrossFit,96,621,13:16,Absent\n31,2024-03-10,18,Male,Monthly,Cardio,52,455,9:43,Present\n32,2024-12-19,19,Male,Monthly,CrossFit,59,374,19:23,Present\n33,2024-03-21,27,Female,Annual,Strength Training,23,127,22:44,Present\n34,2024-03-17,51,Male,Quarterly,CrossFit,36,208,20:18,Present\n35,2024-12-25,50,Female,Monthly,CrossFit,59,584,17:28,Present\n36,2024-03-14,48,Male,Monthly,Cardio,20,159,7:50,Absent\n37,2024-08-24,49,Female,Annual,Strength Training,81,756,11:16,Absent\n38,2024-03-26,47,Female,Annual,CrossFit,107,779,15:14,Present\n39,2024-05-21,61,Female,Monthly,Strength Training,94,737,8:57,Present\n40,2024-05-25,26,Other,Monthly,Yoga,100,562,5:16,Present\n41,2024-04-27,50,Other,Quarterly,HIIT,51,428,15:05,Present\n42,2024-10-01,26,Male,Annual,HIIT,94,859,7:04,Present\n43,2024-11-26,45,Female,Monthly,HIIT,61,412,8:43,Absent\n44,2024-03-22,19,Male,Monthly,Cardio,81,570,20:36,Absent\n45,2024-08-14,39,Female,Monthly,Yoga,26,208,14:20,Absent\n46,2024-07-01,33,Male,Monthly,CrossFit,56,336,21:50,Absent\n47,2024-12-07,40,Other,Quarterly,Yoga,92,524,19:24,Absent\n48,2024-10-18,32,Female,Monthly,Cardio,63,546,18:26,Absent\n49,2024-07-02,42,Male,Monthly,CrossFit,103,755,16:47,Present\n50,2024-12-04,42,Other,Quarterly,Strength Training,99,746,16:19,Absent\n51,2024-08-11,27,Male,Monthly,Yoga,60,337,9:43,Present\n52,2024-11-22,42,Male,Annual,CrossFit,42,346,5:27,Present\n53,2024-01-01,47,Male,Quarterly,CrossFit,55,286,13:54,Absent\n54,2024-12-02,23,Female,Monthly,CrossFit,115,1086,21:11,Absent\n55,2024-05-07,18,Male,Annual,Cardio,53,483,15:03,Absent\n56,2024-03-02,22,Other,Quarterly,Cardio,44,423,18:47,Present\n57,2024-06-12,37,Male,Monthly,Cardio,37,242,11:54,Present\n58,2024-11-12,39,Other,Annual,Yoga,76,596,9:48,Absent\n59,2024-06-14,59,Female,Monthly,HIIT,47,460,17:00,Absent\n60,2024-03-08,65,Other,Annual,HIIT,57,318,19:47,Present\n61,2024-01-19,54,Female,Annual,Yoga,120,751,20:44,Present\n62,2024-04-08,52,Other,Monthly,Strength Training,113,878,9:42,Present\n63,2024-10-10,43,Female,Quarterly,Strength Training,22,142,22:58,Absent\n64,2024-09-04,55,Male,Quarterly,HIIT,33,248,5:51,Absent\n65,2024-11-09,33,Other,Quarterly,HIIT,37,251,10:56,Present\n66,2024-11-29,29,Male,Quarterly,Cardio,83,683,22:12,Absent\n67,2024-07-17,47,Female,Monthly,Cardio,25,172,5:44,Present\n68,2024-01-16,31,Other,Quarterly,Yoga,42,243,10:34,Present\n69,2024-06-12,34,Male,Quarterly,Cardio,54,515,20:05,Absent\n70,2024-01-18,61,Male,Monthly,CrossFit,32,304,7:12,Absent\n71,2024-06-23,22,Female,Annual,Strength Training,92,715,7:12,Absent\n72,2024-12-26,30,Male,Annual,Cardio,49,378,11:52,Absent\n73,2024-08-29,30,Female,Monthly,HIIT,26,233,17:42,Present\n74,2024-04-01,34,Male,Quarterly,HIIT,58,561,19:50,Present\n75,2024-02-11,33,Female,Monthly,CrossFit,53,340,5:22,Absent\n76,2024-11-22,45,Male,Quarterly,Strength Training,54,522,5:01,Absent\n77,2024-02-20,27,Other,Monthly,HIIT,84,476,22:34,Present\n78,2024-10-17,27,Female,Annual,Cardio,80,549,21:01,Absent\n79,2024-05-10,63,Other,Quarterly,Strength Training,45,265,21:09,Present\n80,2024-08-23,59,Other,Annual,CrossFit,89,502,21:53,Present\n81,2024-12-17,60,Male,Quarterly,Yoga,98,630,21:54,Present\n82,2024-06-03,23,Other,Quarterly,Strength Training,43,228,6:52,Absent\n83,2024-10-17,44,Male,Quarterly,CrossFit,20,148,8:30,Absent\n84,2024-05-26,38,Other,Quarterly,Strength Training,108,605,22:52,Absent\n85,2024-01-23,25,Female,Annual,Yoga,40,364,13:59,Present\n86,2024-02-10,33,Female,Quarterly,Cardio,104,997,7:43,Present\n87,2024-03-04,52,Female,Monthly,CrossFit,115,1098,16:18,Absent\n88,2024-12-14,19,Male,Annual,HIIT,104,713,6:35,Absent\n89,2024-05-19,53,Male,Quarterly,HIIT,37,194,15:22,Present\n90,2024-05-24,18,Male,Quarterly,Cardio,41,342,10:41,Absent\n91,2024-04-04,48,Male,Quarterly,Yoga,71,672,13:50,Absent\n92,2024-07-29,20,Other,Monthly,CrossFit,26,148,9:25,Present\n93,2024-04-15,32,Female,Annual,Yoga,64,562,22:15,Present\n94,2024-08-09,47,Male,Monthly,HIIT,114,937,22:33,Absent\n95,2024-11-05,41,Male,Quarterly,CrossFit,110,865,16:19,Absent\n96,2024-02-10,58,Other,Annual,Strength Training,101,778,10:39,Absent\n97,2024-08-30,59,Female,Monthly,Yoga,110,585,22:57,Present\n98,2024-11-17,58,Other,Monthly,Strength Training,98,721,12:34,Present\n99,2024-01-21,33,Female,Annual,Yoga,49,465,10:14,Absent\n100,2024-10-22,42,Female,Quarterly,CrossFit,69,369,18:31,Present\n101,2024-03-12,51,Male,Annual,HIIT,108,856,9:04,Absent\n102,2024-02-27,36,Male,Annual,CrossFit,48,459,7:03,Absent\n103,2024-03-10,20,Female,Annual,Yoga,89,714,6:34,Present\n104,2024-09-04,64,Male,Monthly,CrossFit,86,796,7:55,Present\n105,2024-06-13,22,Other,Monthly,Strength Training,64,590,19:39,Absent\n106,2024-10-14,37,Female,Annual,Strength Training,108,961,15:30,Present\n107,2024-03-04,30,Other,Annual,HIIT,80,596,9:01,Absent\n108,2024-10-05,64,Other,Quarterly,Cardio,73,623,10:45,Present\n109,2024-10-30,31,Female,Annual,Cardio,28,236,10:08,Absent\n110,2024-05-08,48,Other,Quarterly,CrossFit,25,138,14:03,Present\n111,2024-07-13,18,Male,Quarterly,HIIT,62,429,18:40,Absent\n112,2024-10-24,30,Female,Monthly,HIIT,65,555,19:39,Present\n113,2024-10-23,37,Other,Quarterly,HIIT,120,842,20:17,Present\n114,2024-12-31,42,Male,Quarterly,Yoga,88,761,5:32,Absent\n115,2024-06-09,27,Other,Annual,HIIT,27,203,12:15,Present\n116,2024-06-30,47,Other,Quarterly,CrossFit,42,393,20:17,Absent\n117,2024-08-28,49,Other,Quarterly,Cardio,31,193,9:26,Absent\n118,2024-12-25,64,Other,Quarterly,Yoga,89,668,16:33,Present\n119,2024-02-06,59,Female,Annual,HIIT,39,277,5:25,Absent\n120,2024-05-05,47,Male,Monthly,Strength Training,69,591,9:23,Absent\n121,2024-04-11,64,Male,Annual,Yoga,32,262,8:10,Present\n122,2024-11-19,19,Female,Monthly,Cardio,120,1072,20:51,Absent\n123,2024-06-19,32,Male,Quarterly,CrossFit,50,498,5:42,Absent\n124,2024-12-31,23,Male,Annual,CrossFit,83,748,16:54,Present\n125,2024-12-28,30,Other,Quarterly,HIIT,86,774,21:09,Present\n126,2024-10-17,54,Male,Annual,Yoga,37,194,19:14,Absent\n127,2024-01-05,62,Male,Annual,Strength Training,87,788,11:13,Absent\n128,2024-09-14,18,Other,Monthly,Yoga,28,266,14:38,Absent\n129,2024-12-20,18,Male,Annual,Strength Training,53,415,15:30,Present\n130,2024-08-04,61,Other,Quarterly,Cardio,103,756,5:33,Present\n131,2024-01-16,37,Female,Annual,CrossFit,104,873,17:13,Absent\n132,2024-04-15,18,Male,Quarterly,Cardio,88,828,6:25,Absent\n133,2024-09-12,52,Male,Quarterly,HIIT,84,534,17:02,Present\n134,2024-08-04,37,Other,Annual,Cardio,65,327,5:11,Absent\n135,2024-03-16,59,Other,Monthly,Cardio,44,341,16:15,Absent\n136,2024-02-27,65,Male,Quarterly,Strength Training,113,934,14:09,Absent\n137,2024-03-18,50,Other,Monthly,Cardio,117,878,6:06,Present\n138,2024-07-05,38,Other,Quarterly,Strength Training,98,578,7:43,Present\n139,2024-11-03,34,Male,Annual,Cardio,42,214,20:37,Present\n140,2024-02-04,51,Female,Annual,Yoga,63,466,10:46,Present\n141,2024-12-13,56,Female,Annual,Cardio,67,440,13:38,Present\n142,2024-03-25,38,Female,Annual,HIIT,82,816,9:38,Absent\n143,2024-04-20,20,Other,Annual,Strength Training,80,403,7:40,Absent\n144,2024-01-28,32,Female,Monthly,Yoga,48,476,10:24,Absent\n145,2024-07-11,52,Other,Annual,Strength Training,27,155,16:55,Absent\n146,2024-01-11,20,Other,Monthly,Cardio,56,405,8:19,Present\n147,2024-10-24,38,Female,Quarterly,Cardio,106,808,17:12,Present\n148,2024-08-17,48,Male,Monthly,Yoga,109,793,6:26,Present\n149,2024-05-25,18,Male,Monthly,Strength Training,83,823,13:11,Absent\n150,2024-09-11,64,Other,Quarterly,CrossFit,91,537,6:24,Present\n151,2024-01-13,29,Other,Annual,Yoga,31,268,15:57,Absent\n152,2024-02-10,41,Other,Quarterly,Strength Training,83,819,5:38,Present\n153,2024-10-17,19,Other,Quarterly,CrossFit,65,472,17:58,Absent\n154,2024-01-08,27,Male,Quarterly,CrossFit,66,469,10:50,Present\n155,2024-06-16,20,Male,Annual,CrossFit,52,488,13:11,Absent\n156,2024-06-12,37,Other,Annual,CrossFit,54,487,10:20,Present\n157,2024-10-10,57,Other,Monthly,Strength Training,63,341,6:46,Absent\n158,2024-05-24,65,Other,Monthly,Strength Training,74,667,20:48,Absent\n159,2024-03-14,49,Female,Monthly,HIIT,59,367,20:38,Present\n160,2024-08-29,49,Other,Monthly,HIIT,56,512,16:22,Absent\n161,2024-10-04,26,Female,Annual,Strength Training,100,984,13:25,Absent\n162,2024-05-09,61,Male,Monthly,CrossFit,80,553,17:39,Present\n163,2024-02-05,57,Male,Annual,Yoga,111,1000,17:12,Absent\n164,2024-04-01,23,Female,Quarterly,Cardio,113,645,15:36,Absent\n165,2024-02-24,45,Other,Quarterly,CrossFit,59,299,8:57,Absent\n166,2024-02-27,25,Other,Quarterly,Cardio,81,572,16:00,Present\n167,2024-03-17,50,Female,Monthly,Cardio,47,278,18:58,Present\n168,2024-12-29,47,Male,Annual,HIIT,40,227,14:39,Present\n169,2024-03-19,33,Other,Monthly,CrossFit,39,299,15:27,Present\n170,2024-11-01,19,Male,Monthly,CrossFit,77,402,13:29,Absent\n171,2024-03-15,49,Male,Quarterly,HIIT,92,809,12:17,Absent\n172,2024-12-06,45,Male,Quarterly,Cardio,76,647,11:50,Absent\n173,2024-06-01,38,Male,Annual,CrossFit,28,200,7:15,Absent\n174,2024-03-18,22,Other,Monthly,HIIT,109,965,11:53,Present\n175,2024-12-12,38,Other,Annual,Strength Training,82,560,14:27,Present\n176,2024-07-03,61,Other,Annual,HIIT,31,246,5:42,Absent\n177,2024-12-06,25,Female,Quarterly,Strength Training,107,821,16:27,Present\n178,2024-01-25,41,Other,Annual,CrossFit,47,395,22:22,Absent\n179,2024-09-03,61,Other,Monthly,Cardio,57,408,21:12,Present\n180,2024-07-06,38,Other,Quarterly,Strength Training,48,348,18:39,Present\n181,2024-12-21,54,Other,Quarterly,CrossFit,69,487,19:23,Present\n182,2024-03-17,58,Female,Annual,Cardio,97,862,9:21,Present\n183,2024-05-26,63,Male,Monthly,Yoga,55,525,7:18,Absent\n184,2024-02-06,45,Male,Annual,Cardio,118,775,17:42,Absent\n185,2024-10-30,30,Other,Quarterly,Yoga,72,608,20:50,Present\n186,2024-06-05,34,Male,Monthly,Yoga,94,690,6:17,Absent\n187,2024-02-24,51,Other,Quarterly,HIIT,108,611,17:40,Absent\n188,2024-03-05,59,Female,Monthly,HIIT,71,641,13:46,Absent\n189,2024-04-14,53,Female,Quarterly,Strength Training,98,900,12:30,Absent\n190,2024-12-04,60,Female,Monthly,Strength Training,109,780,11:36,Absent\n191,2024-03-18,40,Female,Quarterly,Cardio,20,113,11:29,Absent\n192,2024-11-18,62,Female,Monthly,Yoga,31,247,13:27,Present\n193,2024-01-04,52,Male,Annual,HIIT,73,456,18:31,Absent\n194,2024-08-17,55,Other,Quarterly,Cardio,105,931,12:24,Present\n195,2024-01-09,30,Male,Annual,Cardio,25,212,14:50,Present\n196,2024-01-31,41,Other,Annual,CrossFit,102,944,8:55,Absent\n197,2024-04-16,39,Female,Quarterly,Yoga,78,666,12:57,Absent\n198,2024-11-15,31,Male,Quarterly,HIIT,33,206,10:45,Present\n199,2024-01-02,61,Other,Monthly,HIIT,106,706,22:05,Present\n200,2024-09-10,48,Other,Quarterly,HIIT,68,565,21:24,Absent\n201,2024-01-05,46,Female,Quarterly,Strength Training,27,246,6:22,Absent\n202,2024-10-15,49,Male,Annual,Cardio,72,591,11:22,Absent\n203,2024-03-14,39,Other,Monthly,CrossFit,52,486,10:01,Absent\n204,2024-07-12,24,Male,Monthly,Cardio,51,275,11:41,Absent\n205,2024-04-14,43,Male,Annual,Strength Training,36,301,14:28,Present\n206,2024-02-22,56,Female,Annual,CrossFit,74,398,19:03,Present\n207,2024-06-28,57,Male,Annual,Cardio,64,474,10:09,Present\n208,2024-05-31,54,Female,Monthly,Strength Training,62,613,10:30,Present\n209,2024-08-21,25,Male,Quarterly,Cardio,106,766,19:32,Absent\n210,2024-02-25,49,Male,Annual,Cardio,120,614,15:58,Absent\n211,2024-01-12,52,Other,Quarterly,Yoga,101,548,15:07,Present\n212,2024-08-25,50,Female,Quarterly,HIIT,69,655,14:23,Absent\n213,2024-09-22,50,Female,Quarterly,CrossFit,34,266,9:27,Present\n214,2024-11-25,64,Female,Monthly,Strength Training,98,769,17:20,Absent\n215,2024-11-30,38,Female,Annual,Cardio,111,1025,21:15,Present\n216,2024-04-07,27,Male,Monthly,Cardio,70,540,14:34,Absent\n217,2024-08-26,41,Other,Annual,Yoga,83,741,17:44,Absent\n218,2024-11-07,52,Male,Annual,Strength Training,92,852,17:03,Present\n219,2024-12-21,62,Other,Monthly,CrossFit,58,368,17:22,Absent\n220,2024-10-21,28,Male,Annual,HIIT,26,169,15:20,Present\n221,2024-05-20,58,Female,Annual,Strength Training,59,466,9:17,Present\n222,2024-02-09,53,Female,Annual,Strength Training,89,593,22:39,Present\n223,2024-12-23,52,Other,Monthly,HIIT,78,608,14:51,Present\n224,2024-07-09,58,Female,Monthly,HIIT,23,227,22:05,Present\n225,2024-03-19,27,Male,Monthly,Yoga,116,816,22:37,Present\n226,2024-05-12,64,Male,Monthly,CrossFit,44,234,16:01,Absent\n227,2024-05-09,24,Male,Quarterly,Strength Training,53,489,7:04,Present\n228,2024-03-04,43,Male,Monthly,CrossFit,29,205,7:21,Present\n229,2024-05-03,40,Other,Annual,Yoga,47,235,16:19,Absent\n230,2024-05-14,41,Other,Quarterly,Cardio,85,512,7:31,Absent\n231,2024-09-04,56,Other,Monthly,CrossFit,64,561,17:26,Absent\n232,2024-05-13,25,Female,Annual,HIIT,45,404,12:57,Absent\n233,2024-08-07,53,Male,Quarterly,HIIT,30,223,12:27,Absent\n234,2024-12-02,18,Other,Annual,Cardio,42,248,11:51,Present\n235,2024-11-30,20,Female,Quarterly,Strength Training,78,619,11:09,Present\n236,2024-12-22,36,Female,Quarterly,Yoga,87,725,20:26,Absent\n237,2024-05-26,50,Female,Annual,Yoga,117,959,11:35,Present\n238,2024-01-16,62,Male,Monthly,Cardio,69,600,15:31,Absent\n239,2024-01-07,36,Other,Annual,Cardio,94,735,15:39,Present\n240,2024-02-23,30,Other,Annual,CrossFit,48,437,10:40,Absent\n241,2024-04-03,33,Male,Annual,Yoga,101,714,11:18,Present\n242,2024-07-25,55,Other,Monthly,Strength Training,105,867,5:35,Absent\n243,2024-10-12,29,Other,Annual,Strength Training,112,654,16:57,Present\n244,2024-01-24,64,Other,Annual,Strength Training,102,549,5:57,Absent\n245,2024-01-16,44,Other,Annual,Strength Training,63,452,11:49,Absent\n246,2024-01-27,18,Male,Annual,HIIT,36,328,5:12,Present\n247,2024-11-29,47,Male,Quarterly,Strength Training,109,1040,19:58,Absent\n248,2024-04-14,43,Male,Monthly,CrossFit,27,204,18:27,Present\n249,2024-09-22,22,Male,Annual,Yoga,65,428,12:41,Absent\n250,2024-02-06,50,Other,Monthly,CrossFit,58,505,22:17,Absent\n251,2024-02-04,41,Other,Monthly,HIIT,68,465,21:12,Present\n252,2024-04-11,60,Other,Monthly,Yoga,77,446,19:33,Absent\n253,2024-04-05,29,Male,Annual,Strength Training,52,431,14:57,Present\n254,2024-06-26,19,Male,Annual,Strength Training,40,362,10:13,Absent\n255,2024-06-25,45,Other,Annual,Cardio,84,476,6:12,Absent\n256,2024-12-19,53,Male,Monthly,Cardio,112,733,6:38,Present\n257,2024-02-20,35,Male,Annual,Yoga,108,785,12:31,Present\n258,2024-12-02,40,Male,Quarterly,CrossFit,92,782,8:39,Present\n259,2024-04-08,49,Female,Quarterly,Cardio,87,622,18:24,Present\n260,2024-12-23,24,Female,Annual,Strength Training,80,512,21:10,Absent\n261,2024-02-08,45,Other,Quarterly,Cardio,56,491,6:08,Absent\n262,2024-02-18,39,Female,Annual,CrossFit,31,171,15:47,Absent\n263,2024-01-15,48,Female,Quarterly,Yoga,44,396,14:12,Absent\n264,2024-08-30,55,Male,Monthly,Yoga,35,320,12:05,Present\n265,2024-07-09,62,Female,Annual,Strength Training,75,639,17:48,Present\n266,2024-08-02,64,Other,Monthly,Yoga,26,192,18:21,Present\n267,2024-10-09,26,Other,Annual,Strength Training,78,500,15:38,Absent\n268,2024-06-26,33,Female,Monthly,CrossFit,31,164,22:28,Absent\n269,2024-03-25,49,Male,Quarterly,Strength Training,70,378,13:14,Present\n270,2024-07-13,59,Female,Annual,HIIT,32,272,13:18,Absent\n271,2024-08-06,63,Male,Quarterly,Yoga,120,1058,12:00,Absent\n272,2024-11-19,23,Female,Quarterly,Strength Training,35,210,21:41,Absent\n273,2024-12-05,65,Other,Annual,HIIT,36,279,11:56,Absent\n274,2024-04-18,18,Other,Quarterly,Cardio,85,499,12:55,Absent\n275,2024-03-05,53,Female,Annual,HIIT,61,415,13:41,Absent\n276,2024-07-26,26,Female,Monthly,Cardio,53,429,20:38,Present\n277,2024-02-04,25,Female,Quarterly,HIIT,106,640,22:52,Present\n278,2024-04-19,38,Female,Quarterly,Cardio,114,1087,8:38,Absent\n279,2024-11-08,21,Female,Annual,HIIT,44,302,16:00,Absent\n280,2024-09-25,58,Male,Monthly,Yoga,34,201,12:40,Present\n281,2024-08-16,35,Female,Quarterly,HIIT,88,618,19:08,Present\n282,2024-08-29,27,Other,Annual,Cardio,32,310,13:27,Present\n283,2024-09-09,24,Female,Monthly,Cardio,50,366,14:26,Absent\n284,2024-08-30,19,Other,Quarterly,CrossFit,89,848,20:00,Absent\n285,2024-05-15,61,Other,Monthly,Cardio,57,303,7:24,Absent\n286,2024-06-11,19,Female,Annual,Cardio,98,931,16:39,Absent\n287,2024-04-13,22,Other,Annual,Strength Training,114,939,5:36,Present\n288,2024-01-19,53,Other,Annual,Cardio,29,177,14:50,Absent\n289,2024-06-28,58,Other,Annual,Cardio,107,629,6:01,Absent\n290,2024-01-05,20,Female,Monthly,HIIT,113,1049,7:49,Absent\n291,2024-04-22,30,Male,Monthly,Yoga,95,668,11:28,Present\n292,2024-08-23,60,Female,Quarterly,Yoga,119,994,17:54,Present\n293,2024-10-12,26,Male,Annual,Strength Training,97,876,21:35,Present\n294,2024-05-30,49,Female,Monthly,Cardio,89,655,13:23,Present\n295,2024-12-22,64,Female,Monthly,CrossFit,54,404,5:23,Present\n296,2024-10-17,41,Other,Annual,Yoga,72,642,5:02,Present\n297,2024-08-23,52,Female,Quarterly,CrossFit,94,588,9:11,Absent\n298,2024-03-22,24,Male,Monthly,Yoga,116,871,14:57,Absent\n299,2024-09-10,47,Female,Quarterly,Cardio,120,900,10:31,Absent\n300,2024-04-07,62,Other,Monthly,CrossFit,92,853,13:32,Present\n301,2024-09-27,59,Male,Annual,CrossFit,42,283,22:14,Present\n302,2024-12-13,38,Male,Monthly,HIIT,23,226,10:23,Absent\n303,2024-10-19,50,Male,Quarterly,CrossFit,92,797,13:33,Absent\n304,2024-04-11,57,Male,Annual,Cardio,108,949,6:48,Absent\n305,2024-11-02,42,Other,Annual,Cardio,46,396,8:09,Present\n306,2024-10-01,65,Male,Monthly,Strength Training,104,941,11:11,Absent\n307,2024-04-09,23,Other,Monthly,Yoga,83,481,5:58,Present\n308,2024-05-21,39,Male,Quarterly,Strength Training,91,830,22:57,Present\n309,2024-07-19,19,Other,Monthly,Cardio,76,669,8:30,Present\n310,2024-06-09,19,Female,Quarterly,Strength Training,46,380,12:44,Absent\n311,2024-08-01,37,Other,Quarterly,CrossFit,120,964,22:42,Present\n312,2024-01-24,31,Other,Quarterly,Cardio,54,441,17:00,Absent\n313,2024-12-01,62,Female,Annual,HIIT,100,935,5:21,Present\n314,2024-03-30,40,Other,Monthly,Yoga,99,599,11:27,Absent\n315,2024-02-13,19,Male,Monthly,CrossFit,79,535,19:03,Present\n316,2024-07-21,28,Other,Quarterly,Cardio,75,422,22:21,Absent\n317,2024-01-07,36,Other,Monthly,Yoga,74,528,12:43,Present\n318,2024-03-17,59,Female,Annual,Yoga,120,797,18:31,Present\n319,2024-07-06,49,Male,Annual,HIIT,3

In [2]:
df=pd.read_csv('daily_gym_attendance_workout_data.csv')
df.head()

,member_id,visit_date,age,gender,membership_type,workout_type,workout_duration_minutes,calories_burned,check_in_time,attendance_status
0,1,2024-10-11,64,Other,Annual,HIIT,28,171,20:04,Absent
1,2,2024-06-01,65,Female,Quarterly,Strength Training,72,650,19:17,Absent
2,3,2024-06-13,45,Male,Quarterly,Cardio,70,633,7:24,Absent
3,4,2024-02-05,35,Female,Monthly,CrossFit,64,362,7:18,Absent
4,5,2024-07-13,26,Female,Quarterly,Yoga,31,262,11:22,Absent

In [3]:
df.info()
print("nulls:\n", df.isna().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Unique members:", df['member_id'].nunique(), "| Total rows:", len(df))
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   member_id                 2600 non-null   int64
 1   visit_date                2600 non-null   object
 2   age                       2600 non-null   int64
 3   gender                    2600 non-null   object
 4   membership_type           2600 non-null   object
 5   workout_type              2600 non-null   object
 6   workout_duration_minutes  2600 non-null   int64
 7   calories_burned           2600 non-null   int64
 8   check_in_time             2600 non-null   object
 9   attendance_status         2600 non-null   object
dtypes: int64(4), object(6)
memory usage: 203.3+ KB
nulls:
 member_id                   0
visit_date                  0
age                         0
gender                      0
membership_type             0
workout_type                0
workout_duration_minutes    0
calories_burned             0
check_in_time               0
attendance_status           0
dtype: int64
Duplicate rows: 0
Unique members: 2600 | Total rows: 2600

         member_id          age  workout_duration_minutes  calories_burned
count  2600.000000  2600.000000               2600.000000      2600.000000
mean   1300.500000    41.947308                 70.162692       523.775385
std     750.699674    13.862067                 28.610264       240.449717
min       1.000000    18.000000                 20.000000       102.000000
25%     650.750000    30.000000                 46.000000       329.000000
50%    1300.500000    42.000000                 70.000000       504.000000
75%    1950.250000    54.000000                 94.000000       691.250000
max    2600.000000    65.000000                120.000000      1186.000000

In [4]:
for c in ['gender','membership_type','workout_type','attendance_status']:
    print(df[c].value_counts(dropna=False), '\n')

gender
Female    886
Other     863
Male      851
Name: count, dtype: int64

membership_type
Annual       903
Monthly      856
Quarterly    841
Name: count, dtype: int64

workout_type
Strength Training    559
Cardio               545
HIIT                 520
CrossFit             509
Yoga                 467
Name: count, dtype: int64

attendance_status
Absent     1350
Present    1250
Name: count, dtype: int64

In [12]:
df = pd.read_csv('daily_gym_attendance_workout_data.csv')

df.columns = df.columns.str.strip().str.lower()
df = df.drop_duplicates().copy()

df['visit_date'] = pd.to_datetime(df['visit_date'])
t = pd.to_datetime(df['check_in_time'].astype(str).str.strip(), format='%H:%M', errors='coerce')
assert t.notna().all(), "Some times failed to parse"

df['check_in_hour'] = t.dt.hour
df['check_in_time'] = t.dt.strftime('%H:%M')
df['month'] = df['visit_date'].dt.month
df['month_name'] = df['visit_date'].dt.month_name()
df['weekday'] = df['visit_date'].dt.day_name()
df['is_weekend'] = df['visit_date'].dt.dayofweek >= 5
df['age_group'] = pd.cut(df['age'], [0,24,34,44,54,120],
                         labels=['<25','25-34','35-44','45-54','55+'])
df['is_present'] = (df['attendance_status'] == 'Present').astype(int)

counts = df['check_in_hour'].value_counts().sort_index()
print(len(counts), counts.sum())   # expect 18 2600

from scipy.stats import chisquare
print(chisquare(counts))

18 2600
Power_divergenceResult(statistic=np.float64(27.072307692307692), pvalue=np.float64(0.05701584883058561))

In [13]:
df.to_csv('gym_clean.csv', index=False)
from google.colab import files
files.download('gym_clean.csv')